version: '3.7'
services:
  mysql:
    image: mysql:5.7
    command: mysqld --verbose --sql-mode="NO_ENGINE_SUBSTITUTION" --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_DATABASE: "testdb"
      MYSQL_USER: "appUser"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 3306:3306
